{% set version = "1.3.15" %}

package:
  name: xmlsec
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xmlsec/xmlsec-{{ version }}.tar.gz
  sha256: baa856b83d0012e278e6f6cbec96ac8128de667ca9fa9a2eeb02c752e816f6d8

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libxmlsec1                             # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pkgconfig
    - lxml >=3.8.0,!=4.7.0
    - libxml2
    - libxmlsec1
    - setuptools
    - setuptools_scm
  run:
    - python
    - lxml >=3.8.0,!=4.7.0
    # hard-pin libxmlsec1 as we are unsure whether they do proper semver
    # https://github.com/conda-forge/xmlsec-feedstock/pull/22#issuecomment-2677831048
    - libxmlsec1 ==1.3.7

test:
  requires:
    - pip
  commands:
    - pip check
    # Check that the correct version is reported by pip
    - "pip list --format json | grep '{\"name\": \"xmlsec\", \"version\": \"{{ version }}\"}'"
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library

extra:
  recipe-maintainers:
    - jaimergp
    - xhochy
