{% set version = "1.3.12" %}

package:
  name: xmlsec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xmlsec/xmlsec-{{ version }}.tar.gz
  sha256: 2c86ac6ce570c9e04f04da0cd5e7d3db346e4b5b1d006311606368f17c756ef9

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pkgconfig
    - lxml >=3.8.0
    - libxml2
    - libxmlsec1
    - setuptools_scm
  run:
    - python
    - lxml >=3.8.0

test:
  requires:
    - pip
  commands:
    - pip check
    # Check that the correct version is reported by pip
    - "pip list --format json | grep '{\"name\": \"xmlsec\", \"version\": \"{{ version }}\"}'"
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library

extra:
  recipe-maintainers:
    - jaimergp
    - xhochy
