{% set version = "1.3.9" %}

package:
  name: xmlsec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xmlsec/xmlsec-{{ version }}.tar.gz
  sha256: 3d13d7b6cb921dbc4d60d00ad00081a038df73a1e69f5bcc3695deb1bf2093b0

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pkgconfig
    - lxml >=3.8.0
    - libxml2
    - libxmlsec1
  run:
    - python
    - lxml >=3.8.0

test:
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library

extra:
  recipe-maintainers:
    - jaimergp
