{% set version = "1.3.14" %}

package:
  name: xmlsec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xmlsec/xmlsec-{{ version }}.tar.gz
  sha256: 934f804f2f895bcdb86f1eaee236b661013560ee69ec108d29cdd6e5f292a2d9

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libxmlsec1                             # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pkgconfig
    - lxml >=3.8.0,!=4.7.0
    - libxml2
    - libxmlsec1 1.3.2
    - setuptools_scm
  run:
    - python
    - lxml >=3.8.0,!=4.7.0
    # Hard-pin this as 1.3.3 removed some deprecated functions.
    - libxmlsec1 1.3.2

test:
  requires:
    - pip
  commands:
    - pip check
    # Check that the correct version is reported by pip
    - "pip list --format json | grep '{\"name\": \"xmlsec\", \"version\": \"{{ version }}\"}'"
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library

extra:
  recipe-maintainers:
    - jaimergp
    - xhochy
