{% set version = "1.3.13" %}

package:
  name: xmlsec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xmlsec/xmlsec-{{ version }}.tar.gz
  sha256: 916f5d78e8041f6cd9391abba659da8c94a4fef7196d126d40af1ff417f2cf86

build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libxmlsec1                             # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pkgconfig
    - lxml >=3.8.0,!=4.7.0
    - libxml2
    - libxmlsec1
    - setuptools_scm
  run:
    - python
    - lxml >=3.8.0,!=4.7.0

test:
  requires:
    - pip
  commands:
    - pip check
    # Check that the correct version is reported by pip
    - "pip list --format json | grep '{\"name\": \"xmlsec\", \"version\": \"{{ version }}\"}'"
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library

extra:
  recipe-maintainers:
    - jaimergp
    - xhochy
